HW2 is completed
GorodHolmik/otus_golang_homework pull request #2
Opened 2022-06-14 15:13 UTC by GorodHolmik

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [x] Пайплайн зелёный - 4 балла
- [x] Добавлены новые юнит-тесты - до 4 баллов
- [x] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-06-19 09:27 UTC, egakupi requested changes
Привет! Спасибо за выполненное домашнее задание! Интересное решение. Здорово, что получилось добавить положительные и отрицательные тесты. Всё работает и работает как надо. Рекомендую поработать над чистотой кода.

В чеклисте студента есть ориентир объема кода. Если всё работает и сильно больше, значит что можно сделать попроще и упростить некоторые моменты.
Как раз это влияет на чистоту кода. Чистый код проще, легче, быстрее читается. 
Предлагаю пройтись по коду, обратить внимание на моменты, которые можно упростить. Начать можно с запуска `go test -cover`. Может дать почву для размышлений, что используется в коде – что нет. 

Если будут вопросы – пишите.

2022-06-19 09:27 UTC, egakupi commented on hw02_unpack_string/unpack.go
> +	Digit     = RuneType("DIGIT")
Данные переменные можно не заводить.
Выигрыш от написание Digit / RuneType("DIGIT") минимальный. При полном написании даже понятное, что это за Digit такой – а это именно RuneType.

2022-06-21 19:52 UTC, GorodHolmik commented on hw02_unpack_string/unpack.go
> +	Digit     = RuneType("DIGIT")
Привет!
Количество кода уменьшил за счет объединения повторяющихся случаев.

`RuneType` убирать не стал, т.к. мне кажется, что так проще понять что конкретно за тип у текущего символа.

2022-06-22 07:44 UTC, egakupi commented on hw02_unpack_string/unpack.go
> +		return Digit
Выше я предложил по коду писать, например тут,`return RuneType("DIGIT")`
Вполне понятно о чем речь и можно не заводить под это дело переменные.
Как у вас получилось, тоже ок.

2022-06-22 07:56 UTC, egakupi approved these changes
Спасибо. Круто получилось упростить! Строк кода меньше и читается легче.

Принято – 10/10.

Успехов дальше!

2022-06-22 13:49 UTC, merged